import { useNavigate } from "react-router-dom"

export default function Landing() {
	const navigate = useNavigate()

	return (
		<div className="min-h-[70vh] flex items-center justify-center">
			<div className="max-w-3xl text-center space-y-8 glass-card p-8">
				<div className="space-y-3">
					<h1 className="text-3xl md:text-4xl app-header-title">
						Understand Deepfakes before you detect them
					</h1>
					<p className="text-slate-300">
						Deepfakes are synthetic images and videos created with AI models that can swap faces,
						mimic voices, or recreate entire scenes. They are generated by neural networks that learn
						to copy real people from large collections of photos and videos.
					</p>
					<p className="text-slate-300">
						While this technology can be used for fun and creative effects, it can also be abused for
						misinformation, fraud, and harassment. Detection tools analyze tiny visual and statistical
						clues to estimate whether a piece of media is likely to be manipulated.
					</p>
					<p className="text-slate-300">
	Because deepfakes are becoming harder to identify with the human eye alone, automated detection 
	systems are essential. These systems examine subtle artifacts—like inconsistencies in lighting, 
	blinking patterns, or pixel-level distortions—that are often invisible to viewers.
</p>

<p className="text-slate-300">
	Our deepfake detection model helps users verify whether digital media has been manipulated, 
	providing more transparency and building trust in an age where synthetic content is increasingly common.
</p>
				</div>

				<div className="flex justify-center">
					<button
						type="button"
						className="btn-primary text-base px-6 py-3"
						onClick={() => navigate("/home")}
					>
						Start Deepfake Detection
					</button>
				</div>
			</div>
		</div>
	)
}


